import test from 'node:test';
import assert from 'node:assert/strict';
import {TASK,fixtures} from '../src/public/data.js';
import * as D from '../src/public/domain.js';
const now=1_800_000_000_000;
const input=()=>({criteria:Object.fromEntries(TASK.criteria.map(c=>[c.id,{status:'observed',note:'Explicó el movimiento con evidencia concreta.'}])),observationMethod:'written',changedObserved:true,revisionNote:'Explicó por qué la devolución a tarjeta no afecta el efectivo.',seconds:420});
function reviewed(){return D.reviewSession(fixtures()[0],input(),now);}
function authorized(){const s=D.approveResult(reviewed(),true,now+1);return D.authorizeShare(s,{recipient:'Negocio ficticio A',purpose:'Revisar una muestra para un puesto inicial.',expiresAt:now+86400000,consent:true},now+2);}
test('known fictional cash arithmetic, including changed condition',()=>{assert.equal(D.referenceClosing(),1020);assert.equal(D.referenceClosing(true),1140);});
test('intake blocks missing reviewer, reversed deadlines and scope consent',()=>{const good={candidate:'Demo A',reviewer:'Demo B',organization:'Tienda demo',dueAt:now+86400000,reviewDueAt:now+3*86400000,scopeConfirmed:true};assert.throws(()=>D.createSession({...good,reviewer:''},now));assert.throws(()=>D.createSession({...good,reviewDueAt:now+1},now));assert.throws(()=>D.createSession({...good,scopeConfirmed:false},now));assert.equal(D.createSession(good,now).state,'invited');});
test('review cannot claim a live revision that was not observed',()=>{assert.throws(()=>D.reviewSession(fixtures()[0],{...input(),changedObserved:false},now));});
test('candidate-first review cannot be exported or shared before accuracy approval',()=>{const s=reviewed();assert.equal(s.state,'reviewed_private');assert.throws(()=>D.authorizeShare(s,{recipient:'Demo',purpose:'Demo purpose',expiresAt:now+10000,consent:true},now));assert.throws(()=>D.createProof(s,'invented',now));});
test('correction revokes recipient access and blocks approval until re-review',()=>{const s=authorized(),id=s.shares[0].id;const c=D.requestCorrection(s,'Se omitió mi explicación de la devolución.',now+3);assert.throws(()=>D.createProof(c,id,now+4));assert.throws(()=>D.approveResult(c,true,now+4));assert.ok(c.shares[0].revokedAt);const corrected=D.reviewSession(c,input(),now+5);assert.equal(corrected.correction,null);assert.equal(corrected.approvedAt,null);});
test('review edits invalidate previous candidate approval and share permissions',()=>{const s=authorized(),id=s.shares[0].id;const updated=D.reviewSession(s,input(),now+3);assert.equal(updated.approvedAt,null);assert.throws(()=>D.createProof(updated,id,now+4));});
test('recipient revocation and expiration both block future proof copies',()=>{const s=authorized(),id=s.shares[0].id;assert.equal(D.createProof(s,id,now+4).authorization.recipient,'Negocio ficticio A');assert.throws(()=>D.createProof(D.revokeShare(s,id,now+5),id,now+6));assert.throws(()=>D.createProof(s,id,now+2*86400000));assert.throws(()=>D.createProof(s,'other-recipient',now+4));});
test('missing observations remain private and a retry has no failure label',()=>{const v=input();v.criteria.trace.status='not_observed';const s=D.reviewSession(fixtures()[0],v,now);assert.equal(s.review.complete,false);assert.throws(()=>D.approveResult(s,true,now+1));assert.equal(D.restartSession(s,now+2).state,'invited');});
test('malformed restored review is rejected instead of crashing candidate view',()=>{const s=fixtures()[0];s.state='reviewed_private';assert.throws(()=>D.validateSavedState({schema:1,sessions:[s]}));});
